include(
    Modules.app,
    Modules.presentation,
    Modules.tools,
    Modules.featureUserAccountImpl,
    Modules.featureUserAccountApi,
    Modules.featureNewsFeedImpl,
    Modules.featureNewsFeedApi,
    Modules.coreUi,
    Modules.commonApi,
    Modules.dataSourceImpl,
    Modules.dataSourceApi
)